### PR TITLE
Update to v2.1

### PR DESCRIPTION
**Pull request by digitallysavvy**
Updated Agora VideoUIKit for React Web to use v2.1 of the Agora React SDK.

New web-component without 3rd party libraries to handle wrapping React component as HTML component. New web-component uses Vite instead of CreateReactApp.

### CODE REVIEW

**Review by tadaspetra — CHANGES_REQUESTED** [review]
If you turn off the camera, the mic gets muted as well

**Review by tadaspetra — CHANGES_REQUESTED** [review]
If you change roles to audience, then come back to host, the camera and mic do not work

**Review by tadaspetra — COMMENTED** [review]
If you have 4+ members the UI doesn't fit within the screen anymore, and expands vertically. 

Might not be a UI Kit issue, and just a quirk in the example

**Comment by digitallysavvy** [comment]
> If you have 4+ members the UI doesn't fit within the screen anymore, and expands vertically.
> 
> Might not be a UI Kit issue, and just a quirk in the example

I tested this issue and the UI expands well beyond 4 users.

Screenshot 2024-04-17 at 4 11 35 PM

Screenshot 2024-04-17 at 4 15 55 PM

**Comment by tadaspetra** [comment]
> I tested this issue and the UI expands well beyond 4 users.
> 
> Screenshot 2024-04-17 at 4 11 35 PM Screenshot 2024-04-17 at 4 15 55 PM

My comment wasn't really clear here. But you can see in the floating view (the second one) that the blue bottom menu is no longer visible unless you scroll, this only happens when there is 4+ people. At 3, it's still visible.

**Pull request closed without merging**
